# Site settings
title: Surpiece blog
description: "Surpiece blog"
url: "http://www.surpiece.com"
author:
  name: "Bugra Ozkan"
  email: "info@surpiece.com"
  url: "http://www.surpiece.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
include_footer: false
reverse: false